apiVersion: v1
kind: PersistentVolume
metadata:
  name: drupal-pv
  labels:
    pv: drupal-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: slow
  mountOptions:
    - hard
    - nfsvers=4.1
  hostPath:
    path: /drupal-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: drupal-pvc
spec:
  selector:
    matchLabels:
      pv: drupal-pv
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  volumeName: drupal-pv
---
apiVersion: v1
kind: Service
metadata:
  name: drupal-service
spec:
  type: NodePort
  selector:
    app: drupal
  ports:
  - port: 80
    nodePort: 30095
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: drupal
  labels:
    app: drupal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drupal
  template:
    metadata:
      labels:
        app: drupal
    spec:
      containers:
      - name: drupal
        image: drupal:8.6
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        volumeMounts:
          - mountPath: /var/www/html/modules
            name: data
            subPath: modules
          - mountPath: /var/www/html/profiles
            name: data
            subPath: profiles
          - mountPath: /var/www/html/sites
            name: data
            subPath: sites
          - mountPath: /var/www/html/themes
            name: data
            subPath: themes
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: drupal-pvc
