apiVersion: v1
kind: PersistentVolume
metadata:
  name: drupal-pv
  labels:
    pv: drupal-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: slow
  hostPath:
    path: /drupal-data
    type: Directory
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: drupal-pvc
spec:
  selector:
    matchLabels:
      pv: drupal-pv
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  volumeName: drupal-pv
  storageClassName: slow
---
apiVersion: v1
kind: Service
metadata:
  name: drupal-service
spec:
  type: NodePort
  selector:
    app: drupal
  ports:
  - port: 80
    nodePort: 30095
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: drupal
  labels:
    app: drupal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drupal
  template:
    metadata:
      labels:
        app: drupal
    spec:
      initContainers:
        - name: init-sites-volume
          image: drupal:8.6
          volumeMounts:
            - mountPath: /data
              name: drupal-pvc
          command:
          - "/bin/bash"
          - "-c"
          args:
            - "cp -r /var/www/html/sites/ /data/; chown www-data:www-data /data/ -R"
      containers:
      - name: drupal
        image: drupal:8.6
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        volumeMounts:
          - mountPath: /var/www/html/modules # Mount path on the container
            name: drupal-pvc
            subPath: modules # Subpath in the mount volume
          - mountPath: /var/www/html/profiles
            name: drupal-pvc
            subPath: profiles
          - mountPath: /var/www/html/sites
            name: drupal-pvc
            subPath: sites
          - mountPath: /var/www/html/themes
            name: drupal-pvc
            subPath: themes
      volumes:
        - name: drupal-pvc
          persistentVolumeClaim:
            claimName: drupal-pvc
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: drupal-pv
  labels:
    pv: drupal-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: slow
  hostPath:
    path: /drupal-data
    type: Directory
---
# MySQL database side
apiVersion: v1
kind: PersistentVolume
metadata:
  name: drupal-mysql-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: slow
  hostPath:
    path: /drupal-mysql-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: drupal-mysql-pvc
spec:
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: slow
---
apiVersion: v1
kind: Secret
metadata:
  name: drupal-mysql-secret
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: root_password
  MYSQL_DATABASE: drupal-database
  MYSQL_USER: mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: drupal-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drupal-mysql
  template:
    metadata:
      labels:
        app: drupal-mysql
    spec:
      containers:
      - name: drupal-mysql
        image: mysql:5.7
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3306
        volumeMounts:
          - mountPath: /var/lib/mysql
            name: drupal-mysql-pvc
            subPath: dbdata
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                key: MYSQL_ROOT_PASSWORD
                name: drupal-mysql-secret 
          - name: MYSQL_DATABASE
            valueFrom:
              secretKeyRef:
                key: MYSQL_DATABASE
                name: drupal-mysql-secret
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                key: MYSQL_USER
                name: drupal-mysql-secret

      volumes:
        - name: drupal-mysql-pvc
          persistentVolumeClaim:
            claimName: drupal-mysql-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: drupal-mysql-service
spec:
  type: ClusterIP
  selector:
    app: drupal-mysql
  ports:
  - port: 3306